### ISSUE TITLE
Give access to redis object

### ISSUE THREAD

**Issue by mid1221213** [burnersk/Dancer2-Plugin-Redis#15]
Hello,

Why not giving direct access to the Redis object (and not only in the `on_connect` callback), instead of rewriting the methods it already provides?

This way one can thave total control over the Redis Perl object with the ease of configuration in the YAML file.

Thanks.

**Comment by simbabque** [comment]
Can you give an example of what that would look like? Either how you'd implement it, or what you'd want it to be like when you use it.

**Comment by mid1221213** [comment]
It could be used like this, for example:

```
my $redis_object = redis_plugin->connect;
my ($db_pass, $user) = $redis_object->hmget("user:uid:$uid", 'pass', 'user');
```

The functionality to implement being `redis_plugin->connect`.

**Comment by SysPete** [comment]
I've uploaded a new version the following added to the POD:
```
    If you need access to the underlying Redis object you can access this by
    calling the plugin's _redis method:

        my $redis = redis_plugin->_redis;
```
Based on this I'm closing this issue.
